name: Upload releases

on:
  release:
    types:
      - created

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Install Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
    - name: Enable desktop support
      run: flutter config --enable-windows-desktop
    - name: Build Windows app
      run: flutter build windows
    - name: Copy VC redistributables
      run: |
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
      working-directory: ./build/windows/runner/Release
    - name: Create zip
      uses: papeloto/action-zip@v1
      with:
        files: ./build/windows/runner/Release/
        dest: ./windows.zip
    - name: Upload as asset
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './windows.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}      

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Install Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
    - name: Enable desktop support
      run: |
        flutter config --enable-linux-desktop
        sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
    - name: Build Linux app
      run: flutter build linux
    - name: Create zip
      uses: papeloto/action-zip@v1
      with:
        files: ./build/linux/x64/release/bundle/
        dest: ./linux.zip
    - name: Upload as asset
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './linux.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}      

  build_macos:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Install Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
    - name: Enable desktop support
      run: flutter config --enable-macos-desktop
    - name: Build MacOS app
      run: flutter build macos
    - name: Create a dmg
      run: |
        echo "Install create-dmg"
        brew install create-dmg
        cd $MACOS_APP_RELEASE_PATH
        create-dmg \
          --volname "CCExtractor" \
          --window-pos 200 120 \
          --window-size 800 800 \
          --icon-size 130 \
          --text-size 14 \
          --icon "CCExtractor.app" 260 250 \
          --hide-extension "CCExtractor.app" \
          --app-drop-link 540 250 \
          --hdiutil-quiet \
          "macos.dmg" \
          "CCExtractor.app"
    - name: Upload as asset
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './macos.dmg'
        repo-token: ${{ secrets.GITHUB_TOKEN }}      


