name: Create release binaries for the platforms

on:
  release:
    types:
      - created

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Install Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.2.2'
    - name: Enable desktop support
      run: flutter config --enable-windows-desktop
    - name: Build Windows app
      run: flutter build windows
    - name: Copy VC redistributables
      run: |
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
      working-directory: ./build/windows/runner/Release
    - name: Create zip
      uses: papeloto/action-zip@v1
      with:
        files: ./build/windows/runner/Release/
        dest: ./Windows.zip
    - name: Upload as asset
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './Windows.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}      

